language: csharp
solution: Wavefront.AppMetrics.SDK.CSharp.sln
mono: none
dotnet: 2.1.300

before_install:
  - sudo apt-get install -y dotnet-sdk-5.0

install:
 - dotnet restore

script:
 - dotnet build
 - dotnet test test/Wavefront.AppMetrics.SDK.CSharp.Test/Wavefront.AppMetrics.SDK.CSharp.Test.csproj
